### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'seed_model'

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#724]
Hi there, 

I have been trying to run experiments with a fairly new sklearn-extra classifier ([https://github.com/Alex7Li/scikit-learn-extra/tree/master/sklearn_extra](url)). The classifier runs fine on a local dataset. However, when I am trying to run it on an openml task, I am getting an error.

Here is a minimal example: 
```python
import openml
# define classifier
from sklearn_extra.fast_kernel import FKC_EigenPro
clf = FKC_EigenPro()
# get task
task = openml.tasks.get_task(3)
# run model on task
run = openml.runs.run_model_on_task(clf, task)
# publish run on openml
run.publish()

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-53-e1498e67825a> in <module>
      4 task = openml.tasks.get_task(3)
      5 # run model on task
----> 6 run = openml.runs.run_model_on_task(clf, task)
      7 # publish run on openml
      8 run.publish()

/miniconda3/lib/python3.7/site-packages/openml/runs/functions.py in run_model_on_task(model, task, avoid_duplicate_runs, flow_tags, seed, add_local_measures, upload_flow, return_flow)
    104         seed=seed,
    105         add_local_measures=add_local_measures,
--> 106         upload_flow=upload_flow,
    107     )
    108     if return_flow:

/miniconda3/lib/python3.7/site-packages/openml/runs/functions.py in run_flow_on_task(flow, task, avoid_duplicate_runs, flow_tags, seed, add_local_measures, upload_flow)
    172         task, flow = flow, task
    173 
--> 174     flow.model = flow.extension.seed_model(flow.model, seed=seed)
    175 
    176     # We only need to sync with the server right now if we want to upload the flow,

AttributeError: 'NoneType' object has no attribute 'seed_model'

Is there anything I can do to prevent this from happening?
@amueller

**Comment by amueller** [comment]
I haven't looked at this since the extensions got refactored.

It looks like you need to tell openml that the sklearn extension can be used to handle this estimator.
I'm a bit surprised that that's not the fallback / default.

**Comment by hp2500** [comment]
I think I found a workaround. Putting using the estimator in a pipeline seems to solve the issue. 
@amueller

**Comment by mfeurer** [comment]
This appears to have the same root cause as #718 and #720 and will be fixed via #722. Please reopen if this is not the case.

**Comment by hp2500** [comment]
Hi there, unfortunately the issue still persists.

**Comment by amueller** [comment]
Easier to reproduce is this:
```
# define classifier
import openml
from sklearn.linear_model import LogisticRegression

# there needs to be a version specified but this works lol.
__version__ = 0.1

class MyLR(LogisticRegression):
    pass

clf = MyLR()
# get task
task = openml.tasks.get_task(3)
# run model on task
run = openml.runs.run_model_on_task(clf, task)
# publish run on openml
run.publish()
```

> RuntimeError: No extension could be found for flow None: __main__.MyLR

**Comment by amueller** [comment]
It's pretty obvious that this was broken in #647.
The sklearn extension should handle this, but the sklearn extension can handle only things that ``_is_skleanr_flow`` returns ``True`` for, and that's ``',sklearn==' in flow.external_version``

**Comment by amueller** [comment]
Ok so ``get_extension_by_model`` returns ``sklearn`` because ``isinstance(MyLR(), BaseEstimator)`` - which is also not the correct test btw but whatever.

The problem is that the flow that is created from that model is not an sklearn extension flow, because that's created by ``get_extension_by_flow``, and the sklearn.extension module doesn't set include sklearn in its ``external_version``, it's only including the sklearn version in the tags:

https://github.com/openml/openml-python/blob/56fcc00cb16b102e4778c1f1dadd7d9919e9eca4/openml/extensions/sklearn/extension.py#L420

There are two obvious fixes:
a) When creating the flow, allow setting the extension directly, because we know what the extension is supposed to be.

b) include the sklearn version in the external version

I feel we should be doing both possibly?

**Comment by amueller** [comment]
damn meant to comment on #734
